// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `au-mcp-sdk`.

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface AdapterPresentationMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  description: string
  label?: string
}

export interface AdapterRuntimeMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Refined Number, >= 0, integer */
  contractVersion: number
  agentBinary: string
  launchEntry: string
  skillsEntry: string
  injectEntry: string
}

/**
 * A named bundle of the capability surface an agent launches with — injected skills, always-on
 * context, visible tools, and session governance. Quick-loaded at launch; the ad-hoc picker is
 * an unsaved instance.
 */
export interface AgentProfile {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The skills to inject, as references to mcp.skill instances. Each resolves to its owner's
   * plugin dir at launch (gen-skills --skills). Absent = every discovered skill; an empty
   * list = none.
   */
  skills?: Ref<'mcp.skill'>[]
  /**
   * The always-on context to inject, as references to mcp.inject instances. Each resolves to
   * its owner's plugin dir at launch (gen-inject --inject). An inject's markdown body lands in
   * context unconditionally at session start — the third agent-facing delivery class beside
   * skills and tools, and the only PREPAID one (its full body costs every session before the
   * first turn). The OPEN model DIVERGES here: absent does NOT mean "all". Absent = the
   * role-scoped DEFAULT SET (entry/edit injects fire, dep/discover are opt-in); an empty list
   * = none; a subset = exactly those. A consumed dependency offers context, it never imposes it.
   */
  inject?: Ref<'mcp.inject'>[]
  /**
   * The tools the session may see, as def-refs to mcp.tool subtypes. The daemon resolves this
   * allowlist from the profile graph (there is no AU_MCP_TOOLS launch env). Absent = every
   * discovered tool; an empty list = no tools; a subset = exactly those. Visibility is the whole
   * axis — a tool's engine access is its own declaration on its def, with no human knob over it.
   */
  tools?: DefRef<'mcp.tool'>[]
  /**
   * The native tools this session may use, as a whitelist (the native-tool counterpart to `tools`).
   * Resolved DAEMON-SIDE from this profile at session-open, like `tools` (no AU_MCP_NATIVE_TOOLS env).
   * Tri-state: absent = every native tool
   * (the hard default); an empty list = NO native tool; a list = ONLY those. A whitelist with no
   * exceptions — nothing is implicitly allowed; the agent is pointed at the au_* gate tools for the
   * rest. String names (adapter-declared native tools like `Bash`/`WebFetch`), not engine type-defs.
   */
  nativeToolAllowlist?: string[]
  /**
   * The hooks this session runs, as def-refs to mcp.hook subtypes — the off-switch. Governs the
   * NON-critical hooks: tri-state like `tools` (absent = every hook; an empty list = only the critical
   * ones; a subset = those + the critical ones). A `critical` hook is MANDATORY — it always runs and
   * cannot be excluded; listing one here is redundant and the validator complains. Config
   * (`hookConfig`) is a SEPARATE axis — configuring a hook here does not restrict the others.
   */
  hooks?: DefRef<'mcp.hook'>[]
  /**
   * Typed CONFIG for hooks that take it, as inline-or-ref mcp.hook INSTANCES — each instance's FIELDS
   * are the config (fields-are-config, decision 2606191044 applied to hooks). A hook runs once per
   * configured instance with its typed fields. Inline is fine (config is AUTHORED data, not a selection
   * of pre-existing capabilities, so it diverges from the skills/inject/tools ref-only rule); a ref
   * shares one config across profiles. Independent of `hooks`: this configures, it does not select.
   */
  hookConfig?: [McpHook | Ref<'mcp.hook'>, ...Array<McpHook | Ref<'mcp.hook'>>]
  /**
   * The adapter to launch with, as a def-ref to an mcp.adapter subtype (e.g. mcp.adapter.cc). Unlike the
   * other axes, this is resolved LAUNCHER-SIDE, PRE-launch: the adapter is what SPAWNS the session, so a
   * harness launcher (au-host) reads it off the profile to pick which adapter to run — it is not resolved
   * daemon-side at session-open like `tools`/`hooks`. The launcher locates the adapter's dir from the
   * def's `source.file` and its entries from `adapter-runtime-meta`. Absent = the launcher's default
   * adapter (hard defaults over profiles). See [[spec - mcp.adapter type - the harness adapter as a discovered typed node]].
   */
  adapter?: DefRef<'mcp.adapter'>
}

export interface Mcp {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpAdapter extends Omit<Mcp, 'type'> {
  type: 'mcp.adapter'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface McpHook extends Omit<Mcp, 'type'> {
  type: 'mcp.hook'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * mcp.inject — a package or workspace ships ALWAYS-ON agent context as a typed INSTANCE (injects share
 * ONE shape, so they are instances of this single type, NOT subtypes like mcp.tool). Each instance's
 * markdown BODY is the content, and the instance file is the SEED: its own outbound wikilinks are the
 * hop frontier a `depth` walk follows. Discovered via `instances_of('mcp.inject')`, packed into
 * generated session-start slots under a hard character budget.
 * The ALWAYS-ON delivery class: a tool applies when the agent CALLS it, a skill when its description
 * MATCHES, an inject unconditionally. So an inject is PREPAID — its full body costs on every session,
 * before the user has said anything — which is why budget is a concern of this type and not only of
 * its implementation. The authoring rule that follows: conditional guidance is an mcp.skill,
 * unconditional context is an mcp.inject.
 * There is deliberately NO `always` field (the DEFAULT SET is derived from the owning member's ROLE —
 * entry/edit are in it, dep/discover are opt-in, so a consumed member offers and never imposes), NO
 * `entry`/code (an inject is prose, not a callable), and NO target field (the instance IS the seed).
 * See [[spec - mcp.inject - typed instances whose bodies land in context at session start, hop-expanded and packed across generated hook slots::au-harness]]
 * and [[c - the three agent-facing delivery classes differ by what makes them apply::au-harness]].
 */
export interface McpInject extends Omit<Mcp, 'type'> {
  type: 'mcp.inject'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * the inject's name; the stable slug, and with the owning repo it forms the selection key
   * (`<owner>:<name>`) a host picker toggles and a launch filter matches.
   */
  name: string
  /**
   * what this context IS, for the HUMAN picker deciding whether to pay for it.
   * NOT a trigger. Unlike `mcp.skill.description`, nothing ever matches on this — an inject always
   * applies, so there is no selection for a description to drive. It is a cost-justification label.
   */
  description: string
  /**
   * how many REFERENCE HOPS out from this instance to follow, seeding at the instance's own path.
   * Absent or 0 injects the body alone. Each reached node is injected under its own provenance header.
   * Optional because the common case is a self-contained body.
   * Refined Number, >= 0, integer
   */
  depth?: number
  /**
   * which REFERENCE EDGE KINDS the hop walk follows, as a CLOSED SET over the engine's
   * `references_out` edge classification. An ENUM rather than String[] deliberately: a typo'd kind
   * in a free-string list is accepted and then follows nothing, so the inject silently injects less
   * than it claims. As an enum it is a `field-shape-mismatch` at authoring time. The cost is that a
   * sixth engine kind makes this stale and refuses a legal value — stale-and-loud, over
   * wrong-and-silent.
   * `unknown` is deliberately EXCLUDED: it is the engine's escape hatch for an edge it could not
   * classify, never something an author elects to follow.
   * REQUIRED past depth 1: an unfiltered depth-2 walk through a hub or MOC consumes the entire
   * session budget before the user's first turn, so the blast radius must be stated rather than
   * defaulted. Ignored when `depth` is absent or 0.
   */
  'edge-kinds'?: Array<'field-reference' | 'field-string-wikilink' | 'contributing' | 'navigational'>
  /**
   * what to SHOW per node in the injected block. Default `body` (prose only) — the clean form,
   * since frontmatter is usually routing noise. `body-and-frontmatter` opts into the WHOLE FILE,
   * every frontmatter field included. Use it when the frontmatter carries real content (a typed
   * instance whose fields ARE the data), or to make a frontmatter-edge fanout legible (the link
   * that pulled a node in lives in the source node's frontmatter, which `body` alone would hide).
   * `body` maps to the engine's `body` read, `body-and-frontmatter` to `content` (whole file) —
   * the latter works on plain notes too, unlike the structured `instance` view.
   */
  show?: 'body' | 'body-and-frontmatter'
}

/**
 * mcp.skill — a package ships AGENT GUIDANCE as a typed INSTANCE (skills share ONE shape, so they
 * are instances of this single type, NOT subtypes like mcp.tool). Each instance is a launch-time
 * materialized skill: `name` + `description` drive the harness skill (a Claude Code plugin skill),
 * and the instance's markdown BODY is the skill instructions. Discovered via `instances_of('mcp.skill')`
 * — the launch-time-STATIC mirror of the runtime-DYNAMIC `mcp.tool`. No `body:` contract (the body is
 * freeform prose) and no `entry`/code: a skill is guidance, not a callable.
 * See [[spec - mcp.skill - packages ship agent guidance as typed instances materialized at launch into each harness skill folder::au-harness]]
 * and [[c - skills are launch-time-static the mirror of runtime-dynamic tools::au-harness]].
 */
export interface McpSkill extends Omit<Mcp, 'type'> {
  type: 'mcp.skill'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** the skill's name; becomes the harness skill id (e.g. Claude Code `/<owner>:<name>`). */
  name: string
  /** what the skill is for + when to use it; the harness surfaces this so the agent auto-invokes the skill. */
  description: string
  /**
   * DISCOVERY axis (optional) — the `mcp.tool` leaves this skill is ABOUT, as def-refs, so a reader/host
   * can relate a skill to its tools. NOT materialized into the harness skill.
   */
  'related-tools'?: DefRef<'mcp.tool'>[]
  /**
   * PERMISSIONS axis (optional) — the `mcp.tool` leaves the skill may use, as def-refs; the adapter maps
   * these to the harness's allowed-tools names. Absent means no restriction key is emitted.
   */
  'allowed-tools'?: DefRef<'mcp.tool'>[]
}

export interface McpTool extends Omit<Mcp, 'type'> {
  type: 'mcp.tool'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface PluginRuntimeMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  entry: string
  /** Refined Number, >= 0, integer */
  contractVersion: number
  shapes?: ['observer' | 'mediator' | 'stamper' | 'session-start', ...Array<'observer' | 'mediator' | 'stamper' | 'session-start'>]
  deps?: string[]
  tier?: 'gate' | 'floor' | 'policy'
  critical?: boolean
  requiresContinuity?: boolean
}

export interface ReadPreconditionMeta extends Omit<ToolPreconditionMeta, 'type'> {
  type: 'read-precondition-meta'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  onFiles: [Ref<'file'>, ...Array<Ref<'file'>>]
}

export interface RequiredScopeMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * the capabilities that must be AVAILABLE in the session, as type-def refs. A tool IS a typed def,
   * so one ref shape covers "tool `au_declare` available" and "type `T` resolvable" uniformly;
   * requiring a type/tool a member owns also covers "that member mounted" (an unmounted member's ref
   * does not resolve). Each value is a def-ref wikilink, e.g. `[[au_declare::au-provenance]]`. Absent
   * means no requirement.
   */
  requires?: DefRef<string>[]
}

/** au-mcp's session-retention policy (the dormancy window). */
export interface RetentionConfig {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * How many days a cleanly-closed (dormant) session's durable store is kept before the age-sweep
   * retires it. A positive integer; absent falls to the 30-day hard default.
   * Refined Number, >= 1, integer
   */
  dormancy_days?: number
}

export interface ServesFilesMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  pathTemplate: string
}

export interface ToolAccessMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * declared engine-broker access. `none` (or the meta absent) — no broker. `read` — a
   * read-only broker (engine reads, mutate denied). `read-write` — the full broker (reads +
   * the governed mutation channel). Default none.
   */
  broker?: 'none' | 'read' | 'read-write'
}

export interface ToolPreconditionMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface ToolPresentationMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  description: string
  guidance?: string
}
